modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "leadthevillagers-reborn"
version = "${version}"
displayName = "LeadTheVillagersReborn"
authors = "Sherlock Luk"
description = '''
Make villagers leashable - rewrite of LeadTheVillagers for newer versions
'''
#logoFile = ""

[[dependencies.leadthevillagers]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.leadthevillagers]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.leadthevillagers]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "leadthevillagers.mixins.json"
